import React from "react";
import type { Metadata } from "next";
import Layouts from "@/src/components/admin";
import { ReduxProvider } from "@/src/redux/provider";

// import LazyLoad from './LazyLoad'

type Props = {};

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
export default function DashboadLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <ReduxProvider>
        <Layouts>
          <main>{children}</main>
        </Layouts>
      </ReduxProvider>
    </>
  );
}
