import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SelectedPage } from '../interface/index'
import Navbar from '@/src/components/Website/Navbar'
import Footer from '@/src/components/Website/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-grey-white`}>
        <Navbar isTopOfPage={false} />

        <main>
        {children}
        </main>

        <Footer />
      </body>
    </html>
  )
}
