import "@/src/app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from '@/src/components/Website/Navbar'
import Footer from '@/src/components/Website/Footer'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navbar isTopOfPage={false} />
      <main>{children}</main>
      <Footer />
    </>
  );
}
